openai_api_key: "Open API Key"
data_directory: "path/to/directory"
data_files_glob: "*.txt"
webpages:
  - "https://en.wikipedia.org/wiki/James_Webb_Space_Telescope"
  - "https://en.wikipedia.org/wiki/Black_hole"
tone: "formal"
persona: "buddha"
