openai_api_key: "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"
data_directory: "base"
data_files_glob: "*.txt"
webpages:
  - "https://en.wikipedia.org/wiki/James_Webb_Space_Telescope"
  - "https://en.wikipedia.org/wiki/Black_hole"
tone: "formal"
persona: "buddha"
